
import ImgCarousel1 from "./images/imgCarousel1.png";
import ImgCarousel2 from "./images/iso-9001-overview-graphic.jpg";
import ImgCarousel3 from "./images/ISO-9001-PDCA-Approach.jpg";
import ImgCarousel4 from "./images/iso-9001-executive-summary.jpg";
import ImgCarousel5 from "./images/certification.jpeg";

import Img__btn1 from "./images/imgCertificatIso.jpg";
import Img__btn2 from "./images/PQC.jpg";
import Img__btn3 from "./images/cartographieMacro4.jpg";
import Img__btn4 from "./images/imgCertificatIso2.jpg";

import ImgPap from "./images/ImgPap.jpg";
import ImgPgp from "./images/ImgPgp.jpg";
import ImgPlab from "./images/ImgPlab.jpg";
import ImgPmq from "./images/ImgPmq.jpg";
import ImgPmrh from "./images/ImgPmrh.jpg";
import ImgPtcom from "./images/ImgPtcom.jpg";
import ImgPms from "./images/ImgPms.jpg";



export const ImgCarousel = [
    {
        image:ImgCarousel1,
        title:"ISO1",
    },
    {
        image:ImgCarousel2,
        title:"ISO2",
    },
    {
        image:ImgCarousel3,
        title:"ISO3",
    },
    {
        image:ImgCarousel4,
        title:"ISO4",
    },
    {
        image:ImgCarousel5,
        title:"ISO5",
    },
   
];

export const Img__btn =[
    {image: Img__btn1},
    {image: Img__btn2},
    {image: Img__btn3},
    {image: Img__btn4}
];

export const ProcessusList=[
    {
        id:1,
        image: ImgPms,
        code:"PMS",
        version:"V3",
        date:"23/01/2020",
        name:"Processus Management Stratégique",
        redacteur:   ["REDACTEUR",
                      "BENMEZIANE Ali",
                      "RMQ",
                      "23/01/2020"
                     ],
        verificateur:["VERIFICATEUR",
                      "SAFIR Foudhil",
                      "Membre CQ",
                      "23/01/2020"
                     ],
        approbateur: ["APPROBATEUR",
                      "AIT ALI Mahmoud",
                      "Président Directeur Général",
                      "23/01/2020"
                     ],
        finaliteProcessus:"Traduire la stratégie de CTH en objectifs et garantir leurs réalisations",
        piloteProcessus:"Président Directeur Général",
        amont:["l'ensemble des processus de CTH",
               "Clients",
               "CA",
               "Groupe",
               "Tous les autres clients"
              ],
        aval:["l'ensemble des processus de CTH",
              "Clients",
              "CA",
              "Groupe",
              "Tous les autres clients"
             ],
        entrees:["Orientations émanant du Groupe",
                 "Réglementation en vigueur (nationale et internationale)",
                 "Résolutions  de l'AGO,  et du Conseil d'Administration",
                 "Budget annuel",
                 "Rapports d'activité internes",
                 "Plan d'action issu de la revue de direction",
                 "Résultats des audits internes et externes",
                 "Analyse des marchés",
                 "Revue du contexte de l'organisme",
                 "Analyse des risques et opportunités" 
                ],
        sorties:["Stratégie de CTH",
                 "Objectifs annuels et pluriannuels",
                 "Politique qualité",
                 "Rapport d'activité et budgets",
                 "Planification des actions de CTH",
                 "Organisation générale de CTH",
                 "Responsabilités dans le Mangement Qualité",
                 "PMS/DOC../20…" 
                ],
        activites:["Définir la vision par une analyse de l'environnement interne et externe, fixer les axes stratégiques et les objectifs",
                   "Analyser les risques et les opportunités",
                   "Elaborer la stratégie de CTH et la planifier",
                   "Elaborer et déployer les axes stratégiques et l'organisation",
                   "Communiquer la stratégie en interne et aux parties externes concernées",
                   "Comparer la réalisation du budget par rapport à sa planification",
                   "Evaluer l'efficacité des processus de CTH, au travers de la Revue de Direction",
                   "Allouer les ressources nécessaires au fonctionnement des processus",
                   "Définir des plans d'actions pour atteindre les axes stratégiques et objectifs définis",
                   "Améliorer la communication en interne et en externe",
                  ],
        moyens:[],
        documents:["PrMS/01 : Procédure de la revue de direction",
                   "EMS/01/02 : Responsabilité dans la Management Qualité",
                   "EMS/01/05 : Tableau de Bord Qualité",
                   "EMS/01/07 : Rapport d'activité",
                   "EMS/01/08 : Matrice d'interaction des processus",
                   "PMS/DOC1/2018 : Contexte de l'organisme CTH",
                  ],
        efficacite:[{objectif:"Améliorer la performance économique",
                     indicateur:["Chiffre d'Affaire Réalisé /  Chiffre d'Affaire  Prévu",
                                 "Valeur Ajoutée Réalisée / Valeur Ajoutée Prévue",
                                 "Résultat Brut d'exploitation Réalisé / Résultat Brut d'exploitation Prévue."]},
                                ],
    },
    {
        id:2,
        image: ImgPmq,
        code:"PMQ",
        version:"V2",
        date:"09/09/2022",
        name:"Processus Management Qualité",
        redacteur:   ["REDACTEUR",
                      "BOUSAHBA Adel",
                      "RMQ",
                      "09/09/2022"
                     ],
        verificateur:["VERIFICATEUR",
                      "KHOUAS Mounir",
                      "Directeur Général Adjoint",
                      "11/09/2022"
                     ],
        approbateur: ["APPROBATEUR",
                      "AMIROUCHE Smain",
                      "Président Directeur Général",
                      "12/09/2022"
                     ],
        finaliteProcessus:"Améliorer en permanence la conformité du SMQ (par une mise en oeuvre), l'efficacité du système de management de la qualité et planifier les actions d'amélioration",
        piloteProcessus:"Responsable du Management de la Quaité",
        amont:["l'ensemble des processus de CTH"],
        aval:["l'ensemble des processus de CTH"],
        entrees:["Politique qualité",
                 "Les objectifs qualité",
                 "Analyse des risques sur les processus",
                 "Retour d'Informations clients",
                 "Les résultats d'audits",
                 "L'analyse des données",
                 "Les fiches de NC produit/service",
                 "Les actions correctives",
                 "Résultats de La revue de direction",
                 "Rapport d'activités des structures",
                 "Documentation SMQ"
                ],
        sorties:["Traitement des  non-conformités réelles ou potentielles",
                 "Actions correctives mises en place",
                 "Plan d'action et d'amélioration",
                 "Besoins en ressources (humaines matérielles et organisationnelle)",
                ],
        activites:["Planification du SMQ (Audits internes, Revue de direction, Formation des instances qualité)",
                   "Réunions du CQ",
                   "Analyse des processus et détermination des risques associés",
                   "Rédaction des procédures et autres documents qualité",
                   "Réalisation des audits qualité interne.",
                   "Vérification de la  conformité des exigences relatives aux produits / services",
                   "Surveillance et mesure des processus à travers les indicateurs de performance",
                   "Analyse des rapports d'audit",
                   "Analyse des résultats des indicateurs et TBQ",
                   "Suivi des actions correctives",
                   "Analyses des risques sur les processus",
                   "Réalisation de la revue de direction",
                   "Amélioration du SMQ",
                  ],
        moyens:["Ressources financières alloués à la formation et autres activités",
                "Instances Qualité (Coordinateurs, PP,RP)",
                "Temps nécessaire au déploiement",
                "Réunions de coordination",
                "Ressources matérielles"
               ],
        documents:["PrMQ/01 : Procédure de maîtrise des informations documentées",
                   "IPrMQ/01/01 : Instruction pour la codification des documents",
                   "PrMQ/02 : Procédure de maîtrise des enregistrements",
                   "PrMQ/03: Procédure de maitrise des éléments de sortie NC-AC",
                   "PrMQ/04: Procédure d'audit qualité interne",
                   "PrMS/01 : Procédure de la revue de direction",
                   "PMS/DOC1/2018 : Contexte CTH"
                  ],
        efficacite:[{objectif:"Evaluer le système de management de la qualité",
                    indicateur:["Taux de réalisation des audits: nombre d'audits réalisés / nombre d'audits prévus",
                                "Taux de mise à jour des documents: nombre de procédures mises à jour / nombre total de procédures"]},
                    {objectif:"Evaluer et optimiser le SMQ par rapport aux besoins et aux objectifs",
                    indicateur:["Taux de réalisation du plan d'action: nombre d'actions d'amélioration réalisées / nombre d'actions prévues"]},
                    {objectif:"Améliorer le SMQ",
                    indicateur:["Nombre d'actions correctives mises en place"]},
                   ],
    },
    {
        id:3,
        image: ImgPmrh,
        code:"PMRH",
        version:"V2",
        date:"09/09/2022",
        name:"Processus Management des Ressources Humaines",
        redacteur:   ["REDACTEUR",
                      "METREF Yakouta",
                      "Pilote Processus",
                      "09/09/2022"
                     ],
        verificateur:["VERIFICATEUR",
                      "KHOUAS Mounir",
                      "Directeur Général Adjoint",
                      "11/09/2022"
                     ],
        approbateur: ["APPROBATEUR",
                      "AMIROUCHE Smain",
                      "Président Directeur Général",
                      "12/09/2022"
                     ],
        finaliteProcessus:"Acquérir et développer les compétences nécessaires et les mettre à la disposition des structure de CTH",
        piloteProcessus:"Responsable des Ressources Humaines",
        amont:["l'ensemble des processus de CTH"],
        aval:["l'ensemble des processus de CTH"],
        entrees:["Législation et réglementation du travail (loi 90-11)",
                 "Nomenclature des postes",
                 "Plan de formation",
                 "Plan prévisionnel de recrutement",
                 "Exigence client pour bénéficier d'une compétence spécifique",
                 "Résultats d'évaluation des compétences",
                 "Résultats de la revue de direction",
                 "Orientation du groupe (directives GERHYD, MRE)",
                 "Instructions de la direction générale",
                 "Convention collective",
                 "Règlement intérieur",
                 "Elément de paie"
                ],
        sorties:["Rapport d'activité",
                 "Rapport de synthèse sur l'évaluation des compétences",
                 "Organigramme",
                 "Fiches emploi-type",
                 "Convention collective en vigueur",
                 "Mise à disposition de compétences demandées",
                 "Attestation de succès suite à des actions de formation",
                 "Fiches d'évaluation de l'efficacité de la formation",
                 "PV de recrutement",
                 "Décision de confirmation au poste",
                 "Fiches de paie"
                ],
        activites:["Expression des besoins en recrutement",
                   "Evaluation des candidats au recrutement",
                   "Evaluation suite à la fin de la période d'essai",
                   "Expression des besoins en formation sous forme de courriers mutuels entre les différentes directions régionales et la direction des ressources humaines et des moyens",
                   "Finalisation d'un tableau des besoins exprimés",
                   "Présentation d'un tableau des offres de formations des différents instituts comprenant les délais et les coûts des formations",
                   "Ciblage des principales formations",
                   "Synthèse et réalisation d'un plan de formation final de l'année en cours",
                   "Evaluation de l'efficacité des formations réalisées",
                   "Evaluation des compétences",
                   "Traitement des éléments de paie",
                  ],
        moyens:["Logiciel BIG RH, BIG PAIE",
                "Ressources financières alloués à la formation et autres activités",
                "Réunions de coordination",
                "Ressources matérielles",
               ],
        documents:["PrMRH/01 : Procédure de formation",
                   "PrMRH/02 : Procédure de recrutement",
                   "PrMRH/05 : Procédure d'élaboration de la Paie",
                  ],
        efficacite:[{objectif:"Développer les compétences",
                     indicateur:["Nombre du personnels évalués/personnels total de l'entreprise"]},
                    {objectif:"Mise à disposition des ressources financière",
                     indicateur:["Taux de consommation du budget de formation"]},
                    {objectif:"Motiver le personnel",
                     indicateur:["Nombre d'avancement et de promotions interne"]},
                    {objectif:"Développer l'efficacité des actions de formation",
                     indicateur:["Nbre de formations réalisées durant le trimestre/Nbre total des formations annuelles"]},
                    {objectif:"Veillez à l'efficacité des formations dispensées",
                     indicateur:["Nombre d'évaluation à froid satisfaisantes (mention excellent et/ou bon)/Nbre d'évaluation total"]},
                    {objectif:"Développer l'efficacité des actions de recrutement",
                     indicateur:["Nbre du personnel recrutés avec période d'essai concluante/Nbre Total de recrutement prévus"]},
                    {objectif:"Diminuer le taux d'absentéisme",
                     indicateur:["Nbre du personnels absents/personnels présents"]},
                   ],
    },
    
    {
        id:4,
        image: ImgPgp,
        code:"PGP",
        version:"V2",
        date:"09/09/2022",
        name:"Processus Gestion de Projet",
        redacteur:   ["REDACTEUR",
                      "BOUDALI Benali",
                      "Pilote Processus",
                      "09/09/2022"
                     ],
        verificateur:["VERIFICATEUR",
                      "KHOUAS Mounir",
                      "Directeur Général Adjoint",
                      "11/09/2022"
                     ],
        approbateur: ["APPROBATEUR",
                      "AMIROUCHE Smain",
                      "Président Directeur Général",
                      "12/09/2022"
                     ],
        finaliteProcessus:"Permettre de maitriser les délais, les coûts et la qualité des prestations exigées par le client",
        piloteProcessus:"Directeur Technique",
        amont:["Management Stratégique",
               "Processus Technico-commercial",
               "Processus Approvisionnement",
               "Processus Essai Laboratoire",
               "Processus Marketing et Vente"
              ],
        aval: ["Management Stratégique",
               "Management Qualité",
               "Processus Technico-commercial",
               "Processus Marketing et Vente"
              ],
        entrees:["Contrat signé",
                 "Ordre de service",
                 "Dossier d'exécution"
                ],
        sorties:["Procès verbal de réception provisoire",
                 "Procès verbal de réception définitif",
                 "Fiche Technique Clôture du Projet",
                 "Attestation de bonne exécution"
                ],
        activites:["Recevoir le contrat signé",
                   "Recevoir et accuser réception de l'ordre de service",
                   "Désigné un chargé de projet en formalisant la fiche 'Ordre de Travail' pour préparer une planification détaillée du projet",
                   "Analyser le contrat et formaliser la fiche technique 'Ouverture de Projet'",
                   "Tenir une réunion avec l'ensemble des acteurs de projet pour l'élaboration",
                   "Organigramme de projet (planning détaillé tâches et responsabilités)",
                   "Suivre la mise en œuvre du  planning de réalisation et formaliser mensuellement la 'Fiche suivi de Projet'",
                   "Tenir les réunions périodiques avec le client et / ou les acteurs de projet",
                   "Tenir une réunion de clôture de projet avec l'ensemble des acteurs pour évaluer la réalisation du projet et formaliser la fiche technique 'Clôture de Projet' (un PV sera visé par les participants)",
                   "informer le responsable Management Qualité de l'entreprise sur l'opportunité de prendre des actions correctives afin d’éviter que les anomalies constatées lors de la réalisation du projet ne se reproduisent à l'avenir",
               ],
        moyens:["Ressources financières alloués à la formation et autres activités",
                "Réunions de coordination",
                "Ressources humaines et matérielles",
                "Equipements de contrôle",
                "Moyens de communication",
                "Flotte de véhicule"
               ],
        documents:["Documents Techniques Réglementaires",
                   "Guides techniques",
                   "PrGP/01",
                   "PrGP/02",
                   "PrGP/03",
                   "PrGP/04",
                   "PrGP/05",
                   "PrGP/06",
                   "PrGP/07",
                   "PrGP/08",
                   "PrGP/09",
                   "PrGP/10",
                   "PrGP/11",
                   "PrGP/12" 
                  ],
        efficacite:[{objectif:"S'assurer que les prestations du Contrôle Technique et les activités connexes se déroulent selon les règles de l'art du métier.",
                           indicateur:["Délai d'approbation:", "IGP.1-Délais réels d'approbation des plans/délais prévus", "NB: Les délais prévus sont définis par le nombre de jours selon le degré de complexité et l'importance des ouvrages  comme suit :","a.Projet normal = 05 jours (structures simples et courantes)","b.Projet complexe = 10 jours (conception compliquée nécessitant l'examen approfondi)","Couverture de chantier:", "IGP.2 -Couverture de chantier : Nombre  de visites  et d'examens Technique", "Nombre de visite :","Projet normal : ≥ 04 PV/mois.", "Projet complexe : ≥ 08 PV/mois.","Formule de calcul : IGP2: (Nombre d'examen technique / Nombre de PV) ≥  03"]},
                         ],
    },
    {
        id:5,
        image: ImgPlab,
        code:"PLAB",
        version:"V1",
        date:"09/09/2022",
        name:"Processus Essai Laboratoire",
        redacteur:   ["REDACTEUR",
                      "MENBER Abdelhakim",
                      "Pilote Processus",
                      "09/09/2022"
                     ],
        verificateur:["VERIFICATEUR",
                      "KHOUAS Mounir",
                      "Directeur Général Adjoint",
                      "26/09/2022"
                     ],
        approbateur: ["APPROBATEUR",
                      "AMIROUCHE Smain",
                      "Président Directeur Général",
                      "27/09/2022"
                     ],
        finaliteProcessus:"Assurer la réalisation d'un essai conformément aux modes opératoires et les normes en vigueur",
        piloteProcessus:"Responsable Laboratoire",
        amont:["Processus technico-commercial",
               "Processus de Gestion de Projet",
               "clients",
              ],
        aval: ["Processus technico-commercial",
               "Processus de Gestion de Projet",
               "Clients"
              ],
        entrees:["Convention ou contrat signés",
                        "Ordre de service (interne et externe)",
                        "Matières premières et réactifs",
                        "Equipements étalonnés",
                        "Normes d'essais en vigueur",
                        "Modes opératoires",
                        "Instructions de travail",
                        "Personnels formés",
                       ],
        sorties:["Essai réalisé",
                        "Bulletin d'essai",
                        "Rapport d'analyse et d'interprétation",
                        "Certificat de conformité"
                       ],
        activites:["Recevoir le PV de prélèvement, l'échantillon et la liste des essais demandés",
                   "NB:Lorsque l'échantillon provient du client directement, le PV de prélèvement peut ne pas être exigé s'il y a un bon de commande",
                   "Procéder à l'identification de l'échantillon conformément à l'instruction IPrRE/01/01 « Instruction Protection de la Propriété du Client»",
                   "Arrêter un programme d'exécution des essais exigés.(Le programme doit présenter au minimum : les essais à réaliser sur l'échantillon, l'échéancier de réalisation et le/(s) responsable chargé(s) de la réalisation",
                   "Recevoir l'ordre de travail",
                   "Réaliser l'essai conformément au mode opératoire et  à la norme applicable",
                   "Consigner les résultats de l'essai sur la fiche d'essais appropriée",
                   "Joindre la fiche d'essai à la liste des essais demandés",
                   "Contrôler la réalisation de l'ensemble des essais exigés contractuellement et parapher l'ensemble des fiches d'essais",
                   "Soumettre la liste d'essais demandés et les fiches d'essais au demandeur (Chef de Dépt Technique)"
                  ],
        moyens:["Techniciens formés",
                "Divers équipements labo",
                "Référentiel ISO 17025",
                "Ressources financières alloués à la formation et autres activités",
                "Réunions de coordination",
                "Ressources matérielles"
               ],
        documents:["PrRE/01 : Procédure de manutention",
                   "PrRE/02 : Procédure Réalisation d'un Essai",
                   "PrRE/03 : Procédure Interprétation",
                   "PrRE/04 : Procédure de Maitrise des équipements de surveillance et de mesure",
                   "IPrRE/01/01 : Instruction Protection de la Propriété du Client",
                   "IPrRE/04/01 : Instruction pour l'étalonnage des scléromètres",
                   "IPrRE/04/02 : Instruction pour la manipulation de la rectifieuse"
                  ],
        efficacite:[{objectif:"Réaliser le programme d'étalonnage dans les délais impartis",
                     indicateur:["Etalonnage et/ou vérification des instruments de contrôle utilisés en laboratoire et sur sur site des clients."]},
                    {objectif:"Augmenter la confiance des clients et de ses partenaires par rapport à la qualité des prestations",
                     indicateur:["Nombre Clients du laboratoire satisfaits/Nbre Clients total."]},
                    {objectif:"Assurer la Qualité des résultats ",
                     indicateur:["Fiabilité des résultats : nombre des travaux non-conforme."]}
                   ],
    },
    
    {
        id:6,
        image: ImgPtcom,
        code:"PTCOM",
        version:"V2",
        date:"09/09/2022",
        name:"Processus Technico-commercial",
        redacteur:   ["REDACTEUR",
                      "Ameur Samir",
                      "Pilote processus",
                      "22/10/2019"
                     ],
        verificateur:["VERIFICATEUR",
                      "BENMEZIANE Ali",
                      "RMQ",
                      "24/10/2019"
                     ],
        approbateur: ["APPROBATEUR",
                      "AIT ALI Mahmoud",
                      "Président Directeur Général",
                      "27/10/2019"
                     ],
        finaliteProcessus:"Garantir ses parts de marché par une écoute efficace des clients du CTH",
        piloteProcessus:"Responsable Technico-commercial",
        amont:["Processus Management Stratégique",
               "clients",
               "parties intéressés pertinentes"
              ],
        aval: ["Processus Gestion de Projet",
               "Processus Réalisation d'un essai",
               "Clients et parties intéresses"
              ],
        entrees:["Etude de marché",
                        "Ecoute client",
                        "Exigences clients (Cahier des charges)" 
                       ],
        sorties:["Revue des exigences clients formalisée",
                        "Contrats signés",
                        "Soumissions non retenues",
                        "Enquête de Satisfaction client",
                        "Rapport d'activité mensuel-Technico-commercial",
                        "Etat des créances et recouvrements",
                        "Analyse des risques sur le processus"
                       ],
        activites:["Analyser les tendances du marché et les opportunités (analyse des risques)",
                   "Cibler les appels d'offre et prendre contact avec les clients et s'assurer de l'identification des besoins des clients",
                   "Étudier l'offre et revoir les exigences conformément à la procédure revue des exigences clients",
                   "Établir l'offre pour les cahiers des charges, et le devis ou convention pour les commandes",
                   "Vérifier les offres, les devis et les conventions",
                   "Déposer l'offre, devis et convention pour signature",
                   "Organiser ou assister aux réunions de coordination et établir le PV de réunion. Dans le cas d'absence de PV, adresser une correspondance à titre de compte rendue au client",
                   "Remettre un questionnaire au client pour mesurer sa satisfaction au cours et à  la fin de chaque prestation",
                   "Collecter, analyser  et traiter les réclamations des clients",
                   "Présenter les résultats d'analyse au RMQ qui les présente à la réunion de coordination et en revue de direction",
                   "Mettre en œuvre les actions d'amélioration pour augmenter la satisfaction des clients",
                   "Elaborer le rapport d'activité mensuel"        
                  ],
        moyens:[],
        documents:["PrTCOM/01 : Procédure écoute client",
                   "PrTCOM/02 : Procédure de revue des exigences clients",
                   "Pr TCOM/03 : Procédure de facturation",
                   "PMS/DOC1/2018 : contexte de l'organisme"
                  ],
        efficacite:[{objectif:"Gagner des contrats",
                     indicateur:["Marché Gré à Gré : Nbre Marchés signés X (leurs Montants en KDA HT)/Nbre total Marchés déposés X (Montant total en KDA HT)",
                                 "Appel d'offre : Nbre Offres Converties en Contrat X/(leurs Montants en KDA HT)/ Nbre Total Offres émises dont on a l'information X (Montant total en KDA HT)"]},
                    {objectif:"Efficacité dans  le traitement des appels d'offre et C.D.C",
                     indicateur:["Rapidité de réponse à un appel d'offres ou à un cahier des charges"]},
                    {objectif:"Améliorer le taux de satisfaction globale des clients",
                     indicateur:["Taux de satisfaction client : Nbre de clients satisfait/clients total"]},
                    {objectif:"Réduire les créances ",
                     indicateur:["Taux de recouvrement des créances : Montant du recouvrement réalisé / Montant du recouvrement prévu"]},
                   ],
    },
    {
        id:7,
        image: ImgPap,
        code:"PAP",
        version:"V2",
        date:"09/09/2022",
        name:"Processus Approvisionnement",
        redacteur:   ["REDACTEUR",
                      "GATER Said",
                      "Pilote Processus",
                      "09/09/2022"
                     ],
        verificateur:["VERIFICATEUR",
                      "KHOUAS Mounir",
                      "Directeur Général Adjoint",
                      "11/09/2022"
                     ],
        approbateur: ["APPROBATEUR",
                      "AMIROUCHE Smain",
                      "Président Directeur Général",
                      "12/09/2022"
                     ],
        finaliteProcessus:"Assurer la satisfaction des besoins en matière d'approvisionnement en fourniture de bureau et autre services",
        piloteProcessus:"Chef Département Moyens",
        amont:["l'ensemble des processus de CTH"],
        aval:["l'ensemble des processus de CTH"],
        entrees:["Demande d'achat",
                        "Bon de commande",
                        "Plan d'investissement",
                        "Fournitures et services",
                        "Liste des prestataires externes évalués",
                        "Conventions et contrats (Prestataires externes)",        
                       ],
        sorties:["Bon de réception",
                        "Bon de livraison",
                        "Service fait",
                        "Inventaires",
                        "Rapport d'activité",
                        "Livraison Fournitures et services",
                        "Suivi de l'évaluation des Prestataires externes"        
                       ],
        activites:["Définir le besoin d'achat",
                   "Traiter la demande d'achat",
                   "Déterminer les critères de sélection des fournisseurs et consulter les fiches d'évaluation des fournisseurs et la liste des fournisseurs approuvés",
                   "Prendre contact avec le fournisseur ; mise au point technique et commercial : négociation (délai, prix, qualité et modalité de paiement sur les conditions de transport et d’emballage et d’entreposage",
                   "Confirmer le fournisseur et passer la commande",
                   "Suivre la commande et gérer la relance",
                   "Constituer le dossier de paiement (Facture définitive, PV de réception utilisateur) et le transmettre à la DFC pour règlement",
                   "Évaluer et réévaluer Prestataires externes",
                   "Vérifier la conformité du produit ou service  commandé aux exigences exprimées par la commande et signer le bon de livraison",
                   "Vérifier la conformité du produit ou service  aux exigences exprimées par la commande avec l'utilisateur et signer un PV de réception",
                   "Établir un bon d'entrée pour le produit",
                   "Remettre le produit à l'utilisateur avec une décharge ou un bon de sortie magasin",
                   "Informer les Responsables d'achats et utilisateurs de la mise à jour des listes des Prestataires approuvés",
                  ],
        moyens:["Ressources financières alloués à la formation et autres activités",
                "Réunions de coordination",
                "Ressources humaines et matérielles"
               ],
        documents:["PrAP/01 : Procédure de maîtrise des  Achats",
                   "PrAP/03 : Procédure de réforme",
                   "PrAP/04 : Procédure d'inventaire des investissements",
                   "PrAP/05 : Procédure de Gestion des biens de moindre valeur",
                   "PrAP/06 : Procédure de Gestion du carburant"
                  ],
        efficacite:[{objectif:"Satisfaire les demandes ainsi que  le suivi de l'efficacité des achats",
                    indicateur:["Délai moyen de traitement d'une commande (de la demande à l'envoi)","Nbre de demande d'achats Satisfaites/Nbre Total de demande d'Achats"]
                          },
                    {objectif:"Suivi des performances des prestataires externes",
                    indicateur:["Nombre de PRE/EXT évalués", "Nombre de PRE/EXT réévalués"]},
                   ],
    },
]



